version: '3'

services:
  sql2017:
    image: rdagumampan/mssql-sandbox
    hostname: 'dockersql2017exp'
    container_name: dockersql2017exp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    tty: true
